//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TactsuitAlyx.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierDefaultHead
        {
            get
            {
                return ((float)(this["intensityMultiplierDefaultHead"]));
            }
            set
            {
                this["intensityMultiplierDefaultHead"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierUnarmedHead
        {
            get
            {
                return ((float)(this["intensityMultiplierUnarmedHead"]));
            }
            set
            {
                this["intensityMultiplierUnarmedHead"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierGunHead
        {
            get
            {
                return ((float)(this["intensityMultiplierGunHead"]));
            }
            set
            {
                this["intensityMultiplierGunHead"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierUnarmedBloater
        {
            get
            {
                return ((float)(this["intensityMultiplierUnarmedBloater"]));
            }
            set
            {
                this["intensityMultiplierUnarmedBloater"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierUnarmedHeadcrab
        {
            get
            {
                return ((float)(this["intensityMultiplierUnarmedHeadcrab"]));
            }
            set
            {
                this["intensityMultiplierUnarmedHeadcrab"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierUnarmedHeadcrabArmored
        {
            get
            {
                return ((float)(this["intensityMultiplierUnarmedHeadcrabArmored"]));
            }
            set
            {
                this["intensityMultiplierUnarmedHeadcrabArmored"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierUnarmedHeadcrabBlack
        {
            get
            {
                return ((float)(this["intensityMultiplierUnarmedHeadcrabBlack"]));
            }
            set
            {
                this["intensityMultiplierUnarmedHeadcrabBlack"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierUnarmedHeadcrabFast
        {
            get
            {
                return ((float)(this["intensityMultiplierUnarmedHeadcrabFast"]));
            }
            set
            {
                this["intensityMultiplierUnarmedHeadcrabFast"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierUnarmedHeadcrabRunner
        {
            get
            {
                return ((float)(this["intensityMultiplierUnarmedHeadcrabRunner"]));
            }
            set
            {
                this["intensityMultiplierUnarmedHeadcrabRunner"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierUnarmedFastZombie
        {
            get
            {
                return ((float)(this["intensityMultiplierUnarmedFastZombie"]));
            }
            set
            {
                this["intensityMultiplierUnarmedFastZombie"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierUnarmedPoisonZombie
        {
            get
            {
                return ((float)(this["intensityMultiplierUnarmedPoisonZombie"]));
            }
            set
            {
                this["intensityMultiplierUnarmedPoisonZombie"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierUnarmedZombie
        {
            get
            {
                return ((float)(this["intensityMultiplierUnarmedZombie"]));
            }
            set
            {
                this["intensityMultiplierUnarmedZombie"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierUnarmedZombieBlind
        {
            get
            {
                return ((float)(this["intensityMultiplierUnarmedZombieBlind"]));
            }
            set
            {
                this["intensityMultiplierUnarmedZombieBlind"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierUnarmedZombine
        {
            get
            {
                return ((float)(this["intensityMultiplierUnarmedZombine"]));
            }
            set
            {
                this["intensityMultiplierUnarmedZombine"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierUnarmedAntlion
        {
            get
            {
                return ((float)(this["intensityMultiplierUnarmedAntlion"]));
            }
            set
            {
                this["intensityMultiplierUnarmedAntlion"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierUnarmedAntlionGuard
        {
            get
            {
                return ((float)(this["intensityMultiplierUnarmedAntlionGuard"]));
            }
            set
            {
                this["intensityMultiplierUnarmedAntlionGuard"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierUnarmedManhack
        {
            get
            {
                return ((float)(this["intensityMultiplierUnarmedManhack"]));
            }
            set
            {
                this["intensityMultiplierUnarmedManhack"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierGrabbedByBarnacle
        {
            get
            {
                return ((float)(this["intensityMultiplierGrabbedByBarnacle"]));
            }
            set
            {
                this["intensityMultiplierGrabbedByBarnacle"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float intensityMultiplierConcussionGrenade
        {
            get
            {
                return ((float)(this["intensityMultiplierConcussionGrenade"]));
            }
            set
            {
                this["intensityMultiplierConcussionGrenade"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float intensityMultiplierBugBaitGrenade
        {
            get
            {
                return ((float)(this["intensityMultiplierBugBaitGrenade"]));
            }
            set
            {
                this["intensityMultiplierBugBaitGrenade"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float intensityMultiplierFragGrenade
        {
            get
            {
                return ((float)(this["intensityMultiplierFragGrenade"]));
            }
            set
            {
                this["intensityMultiplierFragGrenade"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float intensityMultiplierSpyGrenade
        {
            get
            {
                return ((float)(this["intensityMultiplierSpyGrenade"]));
            }
            set
            {
                this["intensityMultiplierSpyGrenade"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float intensityMultiplierHandGrenade
        {
            get
            {
                return ((float)(this["intensityMultiplierHandGrenade"]));
            }
            set
            {
                this["intensityMultiplierHandGrenade"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float intensityMultiplierRollerGrenade
        {
            get
            {
                return ((float)(this["intensityMultiplierRollerGrenade"]));
            }
            set
            {
                this["intensityMultiplierRollerGrenade"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float intensityMultiplierRollerMine
        {
            get
            {
                return ((float)(this["intensityMultiplierRollerMine"]));
            }
            set
            {
                this["intensityMultiplierRollerMine"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float intensityMultiplierCombine
        {
            get
            {
                return ((float)(this["intensityMultiplierCombine"]));
            }
            set
            {
                this["intensityMultiplierCombine"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float intensityMultiplierCombineS
        {
            get
            {
                return ((float)(this["intensityMultiplierCombineS"]));
            }
            set
            {
                this["intensityMultiplierCombineS"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float intensityMultiplierCombineGantry
        {
            get
            {
                return ((float)(this["intensityMultiplierCombineGantry"]));
            }
            set
            {
                this["intensityMultiplierCombineGantry"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float intensityMultiplierMetroPolice
        {
            get
            {
                return ((float)(this["intensityMultiplierMetroPolice"]));
            }
            set
            {
                this["intensityMultiplierMetroPolice"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float intensityMultiplierSniper
        {
            get
            {
                return ((float)(this["intensityMultiplierSniper"]));
            }
            set
            {
                this["intensityMultiplierSniper"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float intensityMultiplierStrider
        {
            get
            {
                return ((float)(this["intensityMultiplierStrider"]));
            }
            set
            {
                this["intensityMultiplierStrider"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float intensityMultiplierTurret
        {
            get
            {
                return ((float)(this["intensityMultiplierTurret"]));
            }
            set
            {
                this["intensityMultiplierTurret"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierEnvironmentExplosion
        {
            get
            {
                return ((float)(this["intensityMultiplierEnvironmentExplosion"]));
            }
            set
            {
                this["intensityMultiplierEnvironmentExplosion"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierEnvironmentLaser
        {
            get
            {
                return ((float)(this["intensityMultiplierEnvironmentLaser"]));
            }
            set
            {
                this["intensityMultiplierEnvironmentLaser"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierEnvironmentFire
        {
            get
            {
                return ((float)(this["intensityMultiplierEnvironmentFire"]));
            }
            set
            {
                this["intensityMultiplierEnvironmentFire"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierEnvironmentSpark
        {
            get
            {
                return ((float)(this["intensityMultiplierEnvironmentSpark"]));
            }
            set
            {
                this["intensityMultiplierEnvironmentSpark"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierEnvironmentPoison
        {
            get
            {
                return ((float)(this["intensityMultiplierEnvironmentPoison"]));
            }
            set
            {
                this["intensityMultiplierEnvironmentPoison"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierEnvironmentRadiation
        {
            get
            {
                return ((float)(this["intensityMultiplierEnvironmentRadiation"]));
            }
            set
            {
                this["intensityMultiplierEnvironmentRadiation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierDamageExplosion
        {
            get
            {
                return ((float)(this["intensityMultiplierDamageExplosion"]));
            }
            set
            {
                this["intensityMultiplierDamageExplosion"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierDamageLaser
        {
            get
            {
                return ((float)(this["intensityMultiplierDamageLaser"]));
            }
            set
            {
                this["intensityMultiplierDamageLaser"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierDamageFire
        {
            get
            {
                return ((float)(this["intensityMultiplierDamageFire"]));
            }
            set
            {
                this["intensityMultiplierDamageFire"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierDamageSpark
        {
            get
            {
                return ((float)(this["intensityMultiplierDamageSpark"]));
            }
            set
            {
                this["intensityMultiplierDamageSpark"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierPlayerShootPistol
        {
            get
            {
                return ((float)(this["intensityMultiplierPlayerShootPistol"]));
            }
            set
            {
                this["intensityMultiplierPlayerShootPistol"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierPlayerShootShotgun
        {
            get
            {
                return ((float)(this["intensityMultiplierPlayerShootShotgun"]));
            }
            set
            {
                this["intensityMultiplierPlayerShootShotgun"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierPlayerShootSMG
        {
            get
            {
                return ((float)(this["intensityMultiplierPlayerShootSMG"]));
            }
            set
            {
                this["intensityMultiplierPlayerShootSMG"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierPlayerShootDefault
        {
            get
            {
                return ((float)(this["intensityMultiplierPlayerShootDefault"]));
            }
            set
            {
                this["intensityMultiplierPlayerShootDefault"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierFallbackSMG
        {
            get
            {
                return ((float)(this["intensityMultiplierFallbackSMG"]));
            }
            set
            {
                this["intensityMultiplierFallbackSMG"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierPlayerGrenadeLaunch
        {
            get
            {
                return ((float)(this["intensityMultiplierPlayerGrenadeLaunch"]));
            }
            set
            {
                this["intensityMultiplierPlayerGrenadeLaunch"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierFallbackPistol
        {
            get
            {
                return ((float)(this["intensityMultiplierFallbackPistol"]));
            }
            set
            {
                this["intensityMultiplierFallbackPistol"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierFallbackShotgun
        {
            get
            {
                return ((float)(this["intensityMultiplierFallbackShotgun"]));
            }
            set
            {
                this["intensityMultiplierFallbackShotgun"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierKickbackPistol
        {
            get
            {
                return ((float)(this["intensityMultiplierKickbackPistol"]));
            }
            set
            {
                this["intensityMultiplierKickbackPistol"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierKickbackShotgun
        {
            get
            {
                return ((float)(this["intensityMultiplierKickbackShotgun"]));
            }
            set
            {
                this["intensityMultiplierKickbackShotgun"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierKickbackSMG
        {
            get
            {
                return ((float)(this["intensityMultiplierKickbackSMG"]));
            }
            set
            {
                this["intensityMultiplierKickbackSMG"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierHeartBeat
        {
            get
            {
                return ((float)(this["intensityMultiplierHeartBeat"]));
            }
            set
            {
                this["intensityMultiplierHeartBeat"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierHeartBeatFast
        {
            get
            {
                return ((float)(this["intensityMultiplierHeartBeatFast"]));
            }
            set
            {
                this["intensityMultiplierHeartBeatFast"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierHealthPenUse
        {
            get
            {
                return ((float)(this["intensityMultiplierHealthPenUse"]));
            }
            set
            {
                this["intensityMultiplierHealthPenUse"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierHealthStationUse
        {
            get
            {
                return ((float)(this["intensityMultiplierHealthStationUse"]));
            }
            set
            {
                this["intensityMultiplierHealthStationUse"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierHealthStationUseArm
        {
            get
            {
                return ((float)(this["intensityMultiplierHealthStationUseArm"]));
            }
            set
            {
                this["intensityMultiplierHealthStationUseArm"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierBackpackStoreClip
        {
            get
            {
                return ((float)(this["intensityMultiplierBackpackStoreClip"]));
            }
            set
            {
                this["intensityMultiplierBackpackStoreClip"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierBackpackStoreResin
        {
            get
            {
                return ((float)(this["intensityMultiplierBackpackStoreResin"]));
            }
            set
            {
                this["intensityMultiplierBackpackStoreResin"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierBackpackRetrieveClip
        {
            get
            {
                return ((float)(this["intensityMultiplierBackpackRetrieveClip"]));
            }
            set
            {
                this["intensityMultiplierBackpackRetrieveClip"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierBackpackRetrieveResin
        {
            get
            {
                return ((float)(this["intensityMultiplierBackpackRetrieveResin"]));
            }
            set
            {
                this["intensityMultiplierBackpackRetrieveResin"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierItemHolderStore
        {
            get
            {
                return ((float)(this["intensityMultiplierItemHolderStore"]));
            }
            set
            {
                this["intensityMultiplierItemHolderStore"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierItemHolderRemove
        {
            get
            {
                return ((float)(this["intensityMultiplierItemHolderRemove"]));
            }
            set
            {
                this["intensityMultiplierItemHolderRemove"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierGravityGloveLockOn
        {
            get
            {
                return ((float)(this["intensityMultiplierGravityGloveLockOn"]));
            }
            set
            {
                this["intensityMultiplierGravityGloveLockOn"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierGravityGlovePull
        {
            get
            {
                return ((float)(this["intensityMultiplierGravityGlovePull"]));
            }
            set
            {
                this["intensityMultiplierGravityGlovePull"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float intensityMultiplierGravityGloveCatch
        {
            get
            {
                return ((float)(this["intensityMultiplierGravityGloveCatch"]));
            }
            set
            {
                this["intensityMultiplierGravityGloveCatch"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierClipInserted
        {
            get
            {
                return ((float)(this["intensityMultiplierClipInserted"]));
            }
            set
            {
                this["intensityMultiplierClipInserted"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierChamberedRound
        {
            get
            {
                return ((float)(this["intensityMultiplierChamberedRound"]));
            }
            set
            {
                this["intensityMultiplierChamberedRound"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierCough
        {
            get
            {
                return ((float)(this["intensityMultiplierCough"]));
            }
            set
            {
                this["intensityMultiplierCough"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierCoughHead
        {
            get
            {
                return ((float)(this["intensityMultiplierCoughHead"]));
            }
            set
            {
                this["intensityMultiplierCoughHead"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float intensityMultiplierShockOnHand
        {
            get
            {
                return ((float)(this["intensityMultiplierShockOnHand"]));
            }
            set
            {
                this["intensityMultiplierShockOnHand"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float intensityMultiplierDefault
        {
            get
            {
                return ((float)(this["intensityMultiplierDefault"]));
            }
            set
            {
                this["intensityMultiplierDefault"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public int sleepDurationHeartBeat
        {
            get
            {
                return ((int)(this["sleepDurationHeartBeat"]));
            }
            set
            {
                this["sleepDurationHeartBeat"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("450")]
        public int sleepDurationHeartBeatFast
        {
            get
            {
                return ((int)(this["sleepDurationHeartBeatFast"]));
            }
            set
            {
                this["sleepDurationHeartBeatFast"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int sleepDurationHeartBeatTooFast
        {
            get
            {
                return ((int)(this["sleepDurationHeartBeatTooFast"]));
            }
            set
            {
                this["sleepDurationHeartBeatTooFast"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("780")]
        public int sleepDurationGrabbityLock
        {
            get
            {
                return ((int)(this["sleepDurationGrabbityLock"]));
            }
            set
            {
                this["sleepDurationGrabbityLock"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public int sleepDurationBarnacleGrab
        {
            get
            {
                return ((int)(this["sleepDurationBarnacleGrab"]));
            }
            set
            {
                this["sleepDurationBarnacleGrab"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float intensityMultiplierFoliageTurret
        {
            get
            {
                return ((float)(this["intensityMultiplierFoliageTurret"]));
            }
            set
            {
                this["intensityMultiplierFoliageTurret"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Steam\\steamapps\\common\\Half-Life Alyx")]
        public string AlyxDirectory
        {
            get
            {
                return ((string)(this["AlyxDirectory"]));
            }
            set
            {
                this["AlyxDirectory"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public int sleepDurationCoughing
        {
            get
            {
                return ((int)(this["sleepDurationCoughing"]));
            }
            set
            {
                this["sleepDurationCoughing"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RightHandIpAddress
        {
            get
            {
                return ((string)(this["RightHandIpAddress"]));
            }
            set
            {
                this["RightHandIpAddress"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LeftHandIpAddress
        {
            get
            {
                return ((string)(this["LeftHandIpAddress"]));
            }
            set
            {
                this["LeftHandIpAddress"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23")]
        public int HapticGunPortNumber
        {
            get
            {
                return ((int)(this["HapticGunPortNumber"]));
            }
            set
            {
                this["HapticGunPortNumber"] = value;
            }
        }
    }
}
